// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Demo.Database.Models;

public partial class vEmployeeDepartmentHistory
{
    public int BusinessEntityID { get; set; }

    public string Title { get; set; }

    public string FirstName { get; set; }

    public string MiddleName { get; set; }

    public string LastName { get; set; }

    public string Suffix { get; set; }

    public string Shift { get; set; }

    public string Department { get; set; }

    public string GroupName { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime? EndDate { get; set; }
}