// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Demo.Database.Models;

public partial class vProductModelInstruction
{
    public int ProductModelID { get; set; }

    public string Name { get; set; }

    public string Instructions { get; set; }

    public int? LocationID { get; set; }

    public decimal? SetupHours { get; set; }

    public decimal? MachineHours { get; set; }

    public decimal? LaborHours { get; set; }

    public int? LotSize { get; set; }

    public string Step { get; set; }

    public Guid rowguid { get; set; }

    public DateTime ModifiedDate { get; set; }
}