// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Demo.Database.Models;

public partial class vProductAndDescription
{
    public int ProductID { get; set; }

    public string Name { get; set; }

    public string ProductModel { get; set; }

    public string CultureID { get; set; }

    public string Description { get; set; }
}